x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'
version: '3'

services:
  collect-appwrite:
    image: appwrite/appwrite:0.15.3
    container_name: collect-appwrite
    <<: *x-logging
    restart: unless-stopped
    networks:
      - collect-appwrite
      - gateway
    volumes:
      - collect-appwrite-uploads:/storage/uploads:rw
      - collect-appwrite-cache:/storage/cache:rw
      - collect-appwrite-config:/storage/config:rw
      - collect-appwrite-certificates:/storage/certificates:rw
      - collect-appwrite-functions:/storage/functions:rw
    depends_on:
      - collect-appwrite-mariadb
      - collect-appwrite-redis
#      - collect-appwrite-clamav
      - collect-appwrite-influxdb
    environment:
      - _APP_ENV
      - _APP_WORKER_PER_CORE
      - _APP_LOCALE
      - _APP_CONSOLE_WHITELIST_ROOT
      - _APP_CONSOLE_WHITELIST_EMAILS
      - _APP_CONSOLE_WHITELIST_IPS
      - _APP_SYSTEM_EMAIL_NAME
      - _APP_SYSTEM_EMAIL_ADDRESS
      - _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
      - _APP_SYSTEM_RESPONSE_FORMAT
      - _APP_OPTIONS_ABUSE
      - _APP_OPTIONS_FORCE_HTTPS
      - _APP_OPENSSL_KEY_V1
      - _APP_DOMAIN
      - _APP_DOMAIN_TARGET
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_SMTP_HOST
      - _APP_SMTP_PORT
      - _APP_SMTP_SECURE
      - _APP_SMTP_USERNAME
      - _APP_SMTP_PASSWORD
      - _APP_USAGE_STATS
      - _APP_INFLUXDB_HOST
      - _APP_INFLUXDB_PORT
      - _APP_STORAGE_LIMIT
      - _APP_STORAGE_PREVIEW_LIMIT
      - _APP_STORAGE_ANTIVIRUS
      - _APP_STORAGE_ANTIVIRUS_HOST
      - _APP_STORAGE_ANTIVIRUS_PORT
      - _APP_STORAGE_DEVICE
      - _APP_STORAGE_S3_ACCESS_KEY
      - _APP_STORAGE_S3_SECRET
      - _APP_STORAGE_S3_REGION
      - _APP_STORAGE_S3_BUCKET
      - _APP_STORAGE_DO_SPACES_ACCESS_KEY
      - _APP_STORAGE_DO_SPACES_SECRET
      - _APP_STORAGE_DO_SPACES_REGION
      - _APP_STORAGE_DO_SPACES_BUCKET
      - _APP_STORAGE_BACKBLAZE_ACCESS_KEY
      - _APP_STORAGE_BACKBLAZE_SECRET
      - _APP_STORAGE_BACKBLAZE_REGION
      - _APP_STORAGE_BACKBLAZE_BUCKET
      - _APP_STORAGE_LINODE_ACCESS_KEY
      - _APP_STORAGE_LINODE_SECRET
      - _APP_STORAGE_LINODE_REGION
      - _APP_STORAGE_LINODE_BUCKET
      - _APP_STORAGE_WASABI_ACCESS_KEY
      - _APP_STORAGE_WASABI_SECRET
      - _APP_STORAGE_WASABI_REGION
      - _APP_STORAGE_WASABI_BUCKET
      - _APP_FUNCTIONS_SIZE_LIMIT
      - _APP_FUNCTIONS_TIMEOUT
      - _APP_FUNCTIONS_BUILD_TIMEOUT
      - _APP_FUNCTIONS_CONTAINERS
      - _APP_FUNCTIONS_CPUS
      - _APP_FUNCTIONS_MEMORY
      - _APP_FUNCTIONS_MEMORY_SWAP
      - _APP_FUNCTIONS_RUNTIMES
      - _APP_EXECUTOR_SECRET
      - _APP_EXECUTOR_HOST
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG
      - _APP_STATSD_HOST
      - _APP_STATSD_PORT
      - _APP_MAINTENANCE_INTERVAL
      - _APP_MAINTENANCE_RETENTION_EXECUTION
      - _APP_MAINTENANCE_RETENTION_ABUSE
      - _APP_MAINTENANCE_RETENTION_AUDIT
      - _APP_PHONE_PROVIDER
      - _APP_PHONE_SECRET

  collect-appwrite-realtime:
    image: appwrite/appwrite:0.15.3
    entrypoint: realtime
    container_name: collect-appwrite-realtime
    <<: *x-logging
    restart: unless-stopped
    networks:
      - collect-appwrite
      - gateway
    depends_on:
      - collect-appwrite-mariadb
      - collect-appwrite-redis
    environment:
      - _APP_ENV
      - _APP_WORKER_PER_CORE
      - _APP_OPTIONS_ABUSE
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_USAGE_STATS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-worker-audits:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-audits
    <<: *x-logging
    container_name: collect-appwrite-worker-audits
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-worker-webhooks:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-webhooks
    <<: *x-logging
    container_name: appwrite-worker-webhooks
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-worker-deletes:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-deletes
    <<: *x-logging
    container_name: collect-appwrite-worker-deletes
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
    volumes:
      - collect-appwrite-uploads:/storage/uploads:rw
      - collect-appwrite-cache:/storage/cache:rw
      - collect-appwrite-functions:/storage/functions:rw
      - collect-appwrite-builds:/storage/builds:rw
      - collect-appwrite-certificates:/storage/certificates:rw
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_STORAGE_DEVICE
      - _APP_STORAGE_S3_ACCESS_KEY
      - _APP_STORAGE_S3_SECRET
      - _APP_STORAGE_S3_REGION
      - _APP_STORAGE_S3_BUCKET
      - _APP_STORAGE_DO_SPACES_ACCESS_KEY
      - _APP_STORAGE_DO_SPACES_SECRET
      - _APP_STORAGE_DO_SPACES_REGION
      - _APP_STORAGE_DO_SPACES_BUCKET
      - _APP_STORAGE_BACKBLAZE_ACCESS_KEY
      - _APP_STORAGE_BACKBLAZE_SECRET
      - _APP_STORAGE_BACKBLAZE_REGION
      - _APP_STORAGE_BACKBLAZE_BUCKET
      - _APP_STORAGE_LINODE_ACCESS_KEY
      - _APP_STORAGE_LINODE_SECRET
      - _APP_STORAGE_LINODE_REGION
      - _APP_STORAGE_LINODE_BUCKET
      - _APP_STORAGE_WASABI_ACCESS_KEY
      - _APP_STORAGE_WASABI_SECRET
      - _APP_STORAGE_WASABI_REGION
      - _APP_STORAGE_WASABI_BUCKET
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG
      - _APP_EXECUTOR_SECRET
      - _APP_EXECUTOR_HOST

  collect-appwrite-worker-databases:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-databases
    <<: *x-logging
    container_name: collect-appwrite-worker-databases
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-worker-builds:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-builds
    <<: *x-logging
    container_name: collect-appwrite-worker-builds
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_EXECUTOR_SECRET
      - _APP_EXECUTOR_HOST
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-worker-certificates:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-certificates
    <<: *x-logging
    container_name: collect-appwrite-worker-certificates
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
    volumes:
      - collect-appwrite-config:/storage/config:rw
      - collect-appwrite-certificates:/storage/certificates:rw
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_DOMAIN
      - _APP_DOMAIN_TARGET
      - _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-worker-functions:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-functions
    <<: *x-logging
    container_name: collect-appwrite-worker-functions
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
      - collect-appwrite-executor
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_FUNCTIONS_TIMEOUT
      - _APP_EXECUTOR_SECRET
      - _APP_EXECUTOR_HOST
      - _APP_USAGE_STATS
      - DOCKERHUB_PULL_USERNAME
      - DOCKERHUB_PULL_PASSWORD

  collect-appwrite-executor:
    image: appwrite/appwrite:0.15.3
    entrypoint: executor
    <<: *x-logging
    container_name: collect-appwrite-executor
    restart: unless-stopped
    stop_signal: SIGINT
    networks:
      collect-appwrite:
      collect-appwrite-runtimes:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - collect-appwrite-functions:/storage/functions:rw
      - collect-appwrite-builds:/storage/builds:rw
      - /tmp:/tmp:rw
    depends_on:
      - collect-appwrite-redis
      - collect-appwrite-mariadb
      - collect-appwrite
    environment:
      - _APP_ENV
      - _APP_VERSION
      - _APP_FUNCTIONS_TIMEOUT
      - _APP_FUNCTIONS_BUILD_TIMEOUT
      - _APP_FUNCTIONS_CONTAINERS
      - _APP_FUNCTIONS_RUNTIMES
      - _APP_FUNCTIONS_CPUS
      - _APP_FUNCTIONS_MEMORY
      - _APP_FUNCTIONS_MEMORY_SWAP
      - _APP_FUNCTIONS_INACTIVE_THRESHOLD
      - _APP_EXECUTOR_SECRET
      - OPEN_RUNTIMES_NETWORK
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG
      - _APP_STORAGE_DEVICE
      - _APP_STORAGE_S3_ACCESS_KEY
      - _APP_STORAGE_S3_SECRET
      - _APP_STORAGE_S3_REGION
      - _APP_STORAGE_S3_BUCKET
      - _APP_STORAGE_DO_SPACES_ACCESS_KEY
      - _APP_STORAGE_DO_SPACES_SECRET
      - _APP_STORAGE_DO_SPACES_REGION
      - _APP_STORAGE_DO_SPACES_BUCKET
      - _APP_STORAGE_BACKBLAZE_ACCESS_KEY
      - _APP_STORAGE_BACKBLAZE_SECRET
      - _APP_STORAGE_BACKBLAZE_REGION
      - _APP_STORAGE_BACKBLAZE_BUCKET
      - _APP_STORAGE_LINODE_ACCESS_KEY
      - _APP_STORAGE_LINODE_SECRET
      - _APP_STORAGE_LINODE_REGION
      - _APP_STORAGE_LINODE_BUCKET
      - _APP_STORAGE_WASABI_ACCESS_KEY
      - _APP_STORAGE_WASABI_SECRET
      - _APP_STORAGE_WASABI_REGION
      - _APP_STORAGE_WASABI_BUCKET
      - DOCKERHUB_PULL_USERNAME
      - DOCKERHUB_PULL_PASSWORD

  collect-appwrite-worker-mails:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-mails
    <<: *x-logging
    container_name: acollect-ppwrite-worker-mails
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_SYSTEM_EMAIL_NAME
      - _APP_SYSTEM_EMAIL_ADDRESS
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_SMTP_HOST
      - _APP_SMTP_PORT
      - _APP_SMTP_SECURE
      - _APP_SMTP_USERNAME
      - _APP_SMTP_PASSWORD
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-worker-messaging:
    image: appwrite/appwrite:0.15.3
    entrypoint: worker-messaging
    <<: *x-logging
    container_name: collect-appwrite-worker-messaging
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
    environment:
      - _APP_ENV
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_PHONE_PROVIDER
      - _APP_PHONE_FROM
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-maintenance:
    image: appwrite/appwrite:0.15.3
    entrypoint: maintenance
    <<: *x-logging
    container_name: collect-appwrite-maintenance
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_DOMAIN
      - _APP_DOMAIN_TARGET
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_MAINTENANCE_INTERVAL
      - _APP_MAINTENANCE_RETENTION_EXECUTION
      - _APP_MAINTENANCE_RETENTION_ABUSE
      - _APP_MAINTENANCE_RETENTION_AUDIT

  collect-appwrite-usage:
    image: appwrite/appwrite:0.15.3
    entrypoint: usage
    container_name: collect-appwrite-usage
    <<: *x-logging
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-influxdb
      - collect-appwrite-mariadb
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_INFLUXDB_HOST
      - _APP_INFLUXDB_PORT
      - _APP_USAGE_AGGREGATION_INTERVAL
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_LOGGING_PROVIDER
      - _APP_LOGGING_CONFIG

  collect-appwrite-schedule:
    image: appwrite/appwrite:0.15.3
    entrypoint: schedule
    container_name: collect-appwrite-schedule
    <<: *x-logging
    restart: unless-stopped
    networks:
      - collect-appwrite
    depends_on:
      - collect-appwrite-redis
    environment:
      - _APP_ENV
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS

  collect-appwrite-mariadb:
    image: mariadb:10.7 # fix issues when upgrading using: mysql_upgrade -u root -p
    container_name: collect-appwrite-mariadb
    <<: *x-logging
    restart: unless-stopped
    networks:
      - collect-appwrite
    volumes:
      - collect-appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
    command: 'mysqld --innodb-flush-method=fsync'

  collect-appwrite-redis:
    image: redis:6.2-alpine
    container_name: collect-appwrite-redis
    <<: *x-logging
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - collect-appwrite
    volumes:
      - collect-appwrite-redis:/data:rw

  # clamav:
  #   image: appwrite/clamav:1.2.0
  #   container_name: collect-appwrite-clamav
  #   restart: unless-stopped
  #   networks:
  #     - collect-appwrite
  #   volumes:
  #     - collect-appwrite-uploads:/storage/uploads

  collect-appwrite-influxdb:
    image: appwrite/influxdb:1.5.0
    container_name: collect-appwrite-influxdb
    <<: *x-logging
    restart: unless-stopped
    networks:
      - collect-appwrite
    volumes:
      - collect-appwrite-influxdb:/var/lib/influxdb:rw

  collect-appwrite-telegraf:
    image: appwrite/telegraf:1.4.0
    container_name: collect-appwrite-telegraf
    <<: *x-logging
    restart: unless-stopped
    networks:
      - collect-appwrite
    environment:
      - _APP_INFLUXDB_HOST
      - _APP_INFLUXDB_PORT

networks:
  gateway:
        external: true
        name: gateway
  collect-appwrite:
  collect-appwrite-runtimes:

volumes:
  collect-appwrite-mariadb:
  collect-appwrite-redis:
  collect-appwrite-cache:
  collect-appwrite-uploads:
  collect-appwrite-certificates:
  collect-appwrite-functions:
  collect-appwrite-builds:
  collect-appwrite-influxdb:
  collect-appwrite-config:
  collect-appwrite-executor: